// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrations, prefer the direct (non-pooled) URL — poolers like
    // Neon's pgBouncer don't support the session-level operations Prisma
    // migrate needs. Falls back to DATABASE_URL for local dev.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
